spring.application.name=fl-platform-api
server.port=8081
server.address=0.0.0.0
# ===============================
# DATASOURCE
# ===============================
#    spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.url=jdbc:postgresql://localhost:5432/federated_platform_db
spring.datasource.username=federated_user
spring.datasource.password=qwertyuiop@1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CorsFilter=TRACE
logging.level.org.springframework.web.cors=TRACE
# You can also try TRACE for FilterChainProxy if needed:
# logging.level.org.springframework.security.web.FilterChainProxy=TRACE

# ===============================
# JWT Configuration
# ===============================
# App will fail to boot if this variable is not provided by the host environment
app.jwt.secret=c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX2ZlZGVyYXRlZF9sZWFybmluZ19wbGF0Zm9ybV90aGF0X2lzX3ZlcnlfbG9uZ19pbmRlZWQ=
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:3600000}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Flower
python.executable.path=${PYTHON_EXECUTABLE_PATH:src/main/resources/scripts/run_init_model.sh}
python.flbat.path=${PYTHON_EXECUTABLE_PATH:src/main/resources/scripts/run_fl_server.sh}
python.script.init-model.path=${PYTHON_SCRIPT_INIT_MODEL_PATH:src/main/resources/scripts/init_model.py}
python.script.fl-server.path=${PYTHON_SCRIPT_FL_SERVER_PATH:src/main/resources/scripts/run_fl_server.sh}
