# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MobileClientNew' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # C++ Core: libtorch with training support
  # After running scripts/build_libtorch_ios.sh, link the pre-built libraries:
  #   pod 'LibTorch-Lite', :podspec => '../third_party/libtorch-ios-arm64/LibTorch-Lite.podspec'
  # Or link manually in Xcode build settings:
  #   Header Search Paths: $(SRCROOT)/../../third_party/libtorch-ios-arm64/include
  #   Library Search Paths: $(SRCROOT)/../../third_party/libtorch-ios-arm64/lib
  #   Other Linker Flags: -ltorch -ltorch_cpu -lc10
  #
  # C++ Core: gRPC
  # After running scripts/build_grpc_ios.sh:
  #   Header Search Paths: $(SRCROOT)/../../third_party/grpc-ios-arm64/include
  #   Library Search Paths: $(SRCROOT)/../../third_party/grpc-ios-arm64/lib
  #   Other Linker Flags: -lgrpc++ -lgrpc -lprotobuf -laddress_sorting -lupb -lre2

  target 'MobileClientNewTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
