#!/usr/bin/env node
// =============================================================================
// FedLearn design-token generator (no dependencies).
// Reads design/tokens.json (the single source of truth) and emits per-platform
// artifacts so web, desktop, and mobile never drift:
//   - frontend/src/styles/tokens.css                 (Tailwind v4 @theme)
//   - fedlearn-desktop/src/renderer/tokens.css       (plain CSS custom properties)
//   - mobile_client/src/theme/tokens.generated.ts    (typed token object)
// Run:  node design/build-tokens.mjs
// =============================================================================
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const T = JSON.parse(readFileSync(join(HERE, 'tokens.json'), 'utf8'));

const NOTE = 'GENERATED by design/build-tokens.mjs — DO NOT EDIT. Edit design/tokens.json and re-run.';
const stripPx = (v) => (typeof v === 'string' && v.endsWith('px') ? Number(v.slice(0, -2)) : v);
// CSS custom-property names must not contain a dot (e.g. the "0.5" space key) — some CSS optimizers
// (lightningcss) warn on it. Sanitize the segment for the emitted var name only.
const cssKey = (k) => String(k).replace(/\./g, '_');

function colorVars(theme, indent = '  ') {
  const out = Object.entries(T.color[theme]).map(([k, v]) => `${indent}--${k}: ${v};`);
  T.color.series.forEach((v, i) => out.push(`${indent}--series-${i + 1}: ${v};`));
  return out;
}

function webCss() {
  const L = [`/* ${NOTE} */`, ':root {'];
  L.push(...colorVars('light'));
  for (const [k, v] of Object.entries(T.radius)) L.push(`  --radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.space)) L.push(`  --space-${cssKey(k)}: ${v};`);
  for (const [k, v] of Object.entries(T.shadow)) L.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.duration)) L.push(`  --duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.ease)) L.push(`  --ease-${k}: ${v};`);
  L.push(`  --font-feature-settings: ${T.font['feature-settings']};`, '}');
  L.push('.dark {', ...colorVars('dark'), '}');
  // @theme inline maps the semantic vars (which flip per .dark) to Tailwind utilities.
  L.push('@theme inline {');
  for (const k of Object.keys(T.color.light)) L.push(`  --color-${k}: var(--${k});`);
  T.color.series.forEach((_, i) => L.push(`  --color-series-${i + 1}: var(--series-${i + 1});`));
  for (const k of Object.keys(T.radius)) L.push(`  --radius-${k}: var(--radius-${k});`);
  for (const k of Object.keys(T.shadow)) L.push(`  --shadow-${k}: var(--shadow-${k});`);
  L.push(
    `  --font-sans: ${T.font.sans};`,
    `  --font-display: ${T.font.display};`,
    `  --font-mono: ${T.font.mono};`,
  );
  for (const [k, s] of Object.entries(T.text)) {
    L.push(`  --text-${k}: ${s.size};`);
    L.push(`  --text-${k}--line-height: ${s.line};`);
    L.push(`  --text-${k}--letter-spacing: ${s.tracking};`);
    L.push(`  --text-${k}--font-weight: ${s.weight};`);
  }
  L.push('}');
  return L.join('\n') + '\n';
}

function desktopCss() {
  const L = [`/* ${NOTE} */`, ':root {'];
  L.push(...colorVars('light'));
  for (const [k, v] of Object.entries(T.radius)) L.push(`  --radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.space)) L.push(`  --space-${cssKey(k)}: ${v};`);
  for (const [k, v] of Object.entries(T.shadow)) L.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.duration)) L.push(`  --duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.ease)) L.push(`  --ease-${k}: ${v};`);
  L.push(
    `  --font-sans: ${T.font.sans};`,
    `  --font-display: ${T.font.display};`,
    `  --font-mono: ${T.font.mono};`,
  );
  for (const [k, s] of Object.entries(T.text)) {
    L.push(`  --text-${k}-size: ${s.size};`);
    L.push(`  --text-${k}-line: ${s.line};`);
    L.push(`  --text-${k}-tracking: ${s.tracking};`);
    L.push(`  --text-${k}-weight: ${s.weight};`);
  }
  L.push(`  --font-feature-settings: ${T.font['feature-settings']};`, '}');
  L.push('.dark, :root.dark {', ...colorVars('dark'), '}');
  return L.join('\n') + '\n';
}

function mobileTs() {
  const obj = {
    colorLight: T.color.light,
    colorDark: T.color.dark,
    series: T.color.series,
    radius: Object.fromEntries(Object.entries(T.radius).map(([k, v]) => [k, stripPx(v)])),
    space: Object.fromEntries(Object.entries(T.space).map(([k, v]) => [k, stripPx(v)])),
    duration: Object.fromEntries(
      Object.entries(T.duration).map(([k, v]) => [k, Number(String(v).replace('ms', ''))]),
    ),
    font: { sans: 'Hanken Grotesk', display: 'Hanken Grotesk', mono: 'JetBrains Mono' },
    text: Object.fromEntries(
      Object.entries(T.text).map(([k, s]) => [k, {
        size: stripPx(s.size), line: stripPx(s.line),
        tracking: stripPx(s.tracking), weight: Number(s.weight),
      }]),
    ),
  };
  return (
    `// ${NOTE}\n` +
    `export const tokens = ${JSON.stringify(obj, null, 2)} as const;\n\n` +
    `export type ColorToken = keyof typeof tokens.colorLight;\n` +
    `export default tokens;\n`
  );
}

function mobileGlobalCss() {
  const L = ['@tailwind base;', '@tailwind components;', '@tailwind utilities;', '', '/*', ` * ${NOTE}`];
  L.push(' * Semantic color variables for NativeWind v4 dark mode: :root = light palette, .dark = dark.');
  L.push(' * NativeWind applies the .dark class from the OS color scheme, so one semantic class');
  L.push(' * (bg-canvas, text-fg, border-hairline, ...) resolves per scheme — no dark: duplication.');
  L.push(' * tailwind.config.js maps each semantic color to var(--color-<name>).');
  L.push(' */');
  L.push(':root {');
  for (const [k, v] of Object.entries(T.color.light)) L.push(`  --color-${k}: ${v};`);
  L.push('}', '', '.dark {');
  for (const [k, v] of Object.entries(T.color.dark)) L.push(`  --color-${k}: ${v};`);
  L.push('}');
  return L.join('\n') + '\n';
}

const targets = [
  ['frontend/src/styles/tokens.css', webCss()],
  ['fedlearn-desktop/src/renderer/tokens.css', desktopCss()],
  ['mobile_client/src/theme/tokens.generated.ts', mobileTs()],
  ['mobile_client/src/theme/global.css', mobileGlobalCss()],
];
for (const [rel, content] of targets) {
  const out = join(ROOT, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, content);
  console.log('wrote', rel);
}
