#pragma once
//
// FedLearnCoreModule.h — the shared C++ (CXX) TurboModule behind bridge/specs/NativeFedLearnCore.ts.
//
// DESIGN: the real federated-learning logic lives in the private `do*` methods, which take/return
// plain bridge::* structs (BridgeTypes.h) and call the verified C++ core (ModelManager,
// FedLearnClient, FederatedLoop). They have NO React Native / JSI dependency, so they are
// version-independent and reasoned about on their own merits. The PUBLIC methods are the thin
// JSI/Promise layer the codegen spec calls; they marshal structs <-> jsi::Object field-by-field
// (no hand-built JSON, fixes A6 §L3) and run each `do*` off the JavaScript thread.
//
// ┌─ VERIFY-BEFORE-BUILD (React Native New Architecture, version-specific) ─────────────────────┐
// │ The base class `react::NativeFedLearnCoreCxxSpec<...>`, the exact JSI method signatures, the │
// │ Promise helper (`react::createPromiseAsJSIValue`), and the CallInvoker are produced/required │
// │ by RN codegen for the PINNED RN version. Run `codegen` (npx react-native codegen) and        │
// │ reconcile the signatures below against the generated `NativeFedLearnCoreCxxSpecJSI.h`. None   │
// │ of this compiles without the RN toolchain; the `do*` logic is the part that is portable.     │
// └────────────────────────────────────────────────────────────────────────────────────────────┘
//
#include <atomic>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include <ReactCommon/TurboModule.h>             // react::TurboModule, CallInvoker  (RN)
#include <jsi/jsi.h>                              // facebook::jsi                     (RN)
// GENERATED by RN codegen from bridge/specs/NativeFedLearnCore.ts (present at build time on the app
// codegen include path). It defines react::NativeFedLearnCoreCxxSpec<T>, whose constructor wires the
// TurboModule methodMap_ to delegate each JS call to this impl's methods. We MUST extend it — extending
// react::TurboModule directly leaves methodMap_ empty, so NO native method is callable from JS.
#include <react/renderer/components/NativeFedLearnCoreSpec/NativeFedLearnCoreSpecJSI.h>

#include "BridgeTypes.h"
#include "fedlearn/DataLoader.h"   // OwnedBatch (owns trainingBatch_'s backing storage)
#include "fedlearn/ExecutorchModel.h"
#include "fedlearn/FedLearnClient.h"
#include "fedlearn/FederatedLoop.h"
#include "fedlearn/ModelManager.h"
#include "fedlearn/Types.h"

namespace fedlearn::bridge {

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// The protocol version this client speaks (must equal the server's; RegisterClient rejects on
// mismatch — E1 / 04 §10.1.2). Bump on any breaking contract change.
inline constexpr int kProtocolVersion = 2;

class FedLearnCoreModule : public react::NativeFedLearnCoreCxxSpec<FedLearnCoreModule> {
 public:
  // dataDir: app-private directory (Android filesDir / iOS Documents) holding the gRPC client
  // cert/key/CA and any on-device training data. Passed by the platform layer (OnLoad / .mm).
  FedLearnCoreModule(std::shared_ptr<react::CallInvoker> jsInvoker, std::string dataDir);
  ~FedLearnCoreModule() override;

  // Platform hooks (set by the Android/iOS layer; not part of the JS spec).
  void setMetricsProvider(std::function<DeviceMetrics()> provider);
  // Wiring of on-device training data is the RN app layer's job (15-LLD §13 task 14). Until then
  // a round throws a clear error. This seam lets the app/test supply a validated batch.
  // NB: named apply* (not set*) so they don't overload the same-named JSI spec methods below — the RN
  // codegen Delegate takes &FedLearnCoreModule::setModelManifest as a member pointer, which must be
  // unambiguous.
  void applyTrainingDataFromFiles(const std::string& inputsF32Path,
                                  const std::vector<int64_t>& inputShape,
                                  const std::string& targetsI64Path);

  // ExecuTorch model load is weights-as-inputs: ModelManager::loadModel needs the trainable
  // param layout + total param count, and the infer .pte (forward(flat,x)->logits) has its OWN
  // sha. The platform layer reads these from the model's sidecar manifest (param_layout /
  // total_param_count / infer_pte path+sha, written by pte_export.py) and supplies them here
  // before loadModel(). (Replaces the old libtorch Module auto-introspection.)
  struct ModelManifest {
    std::vector<fedlearn::ParamSpec> paramLayout;  // trainable name->shape, flat order
    int64_t totalParamCount = 0;                   // incl. frozen, for ModelInfo tier
    std::string inferPtePath;                      // forward(flat,x)->logits graph
    std::string inferSha256;                       // sha of the infer .pte
  };
  void applyModelManifest(const ModelManifest& manifest);

  // ---- JSI spec methods (signatures must match the generated CxxSpec; see header banner) ----
  jsi::Value registerClient(jsi::Runtime& rt, jsi::String serverAddress, jsi::String runId,
                            jsi::String clientId, jsi::String enrollmentToken, bool useTls);
  jsi::Value getServerStatus(jsi::Runtime& rt, jsi::String runId);
  jsi::Value stop(jsi::Runtime& rt);
  // JSI overloads of the setModelManifest / setTrainingDataFromFiles platform hooks: the RN app layer
  // stages the model manifest + on-device data, then drives loadModel + the round loop. They unmarshal
  // on the JS thread and apply on a worker (Promise<void>).
  jsi::Value setModelManifest(jsi::Runtime& rt, jsi::Object manifest);
  jsi::Value setTrainingDataFromFiles(jsi::Runtime& rt, jsi::String inputsF32Path, jsi::Array inputShape,
                                      jsi::String targetsI64Path);
  jsi::Value stageBundleFile(jsi::Runtime& rt, jsi::String filename, jsi::String base64Data);
  jsi::Value loadModel(jsi::Runtime& rt, jsi::String modelPath, jsi::String expectedSha256);
  jsi::Value runDeComFLRound(jsi::Runtime& rt, jsi::String runId, jsi::Object config);
  jsi::Value runFedAvgRound(jsi::Runtime& rt, jsi::String runId, jsi::Object config);
  jsi::Value infer(jsi::Runtime& rt, jsi::String inputJson);
  jsi::Value getDeviceMetrics(jsi::Runtime& rt);

 private:
  // ---- pure logic (no JSI; the portable, correct core) ----
  RegisterResult doRegister(const std::string& serverAddress, const std::string& runId,
                            const std::string& clientId, const std::string& enrollmentToken,
                            bool useTls);
  ServerStatus doGetServerStatus(const std::string& runId);
  void doStop();
  ModelInfo doLoadModel(const std::string& modelPath, const std::string& expectedSha256);
  RoundResult doRunDeComFLRound(const std::string& runId, const RoundConfig& cfg);
  RoundResult doRunFedAvgRound(const std::string& runId, const RoundConfig& cfg);
  InferResult doInfer(const std::string& inputJson);
  DeviceMetrics doGetDeviceMetrics();
  // Base64-decode `base64Data` and write it to dataDir/bundle/<basename(filename)>; returns the path.
  std::string doStageBundleFile(const std::string& filename, const std::string& base64Data);

  // helpers
  void evalBatch(double& outLoss, double& outAccuracy);  // one forward pass on trainingBatch_
  void requireReady() const;                             // model + net + data loaded, else throw

  // Async worker tracking: JSI calls run their do* on a worker thread. The threads are KEPT (not
  // detached) so the destructor / doStop can quiesce them before member teardown — a detached worker
  // capturing `this` would otherwise resume against a freed module on RN bridge reload (use-after-free).
  template <typename Work, typename Build>
  jsi::Value runOnWorker(jsi::Runtime& rt, Work work, Build build);
  void reapFinishedWorkers();  // join+drop completed workers; caller MUST hold workersMutex_
  void joinAllWorkers();       // block until every worker thread has returned

  std::shared_ptr<react::CallInvoker> jsInvoker_;
  std::string dataDir_;

  std::mutex stateMutex_;  // the JS thread calls in; rounds run on a worker — guard shared state
  fedlearn::ModelManager mm_;
  std::unique_ptr<fedlearn::FedLearnClient> net_;
  std::unique_ptr<fedlearn::FederatedLoop> loop_;
  std::unique_ptr<fedlearn::ExecutorchModel> model_;       // loss graph: forward(flat,x,y)->loss
  std::unique_ptr<fedlearn::ExecutorchModel> inferModel_;  // infer graph: forward(flat,x)->logits
  bool modelLoaded_ = false;
  ModelManifest manifest_;
  bool manifestSet_ = false;
  fedlearn::OwnedBatch trainingOwner_;  // owns the batch backing storage
  fedlearn::DataBatch trainingBatch_;   // a view into trainingOwner_ (valid while the owner lives)
  bool dataLoaded_ = false;
  std::string clientId_;
  std::function<DeviceMetrics()> metricsProvider_;

  // In-flight JSI worker threads (see runOnWorker); joined in the destructor/doStop before teardown.
  struct Worker { std::thread thread; std::shared_ptr<std::atomic<bool>> done; };
  std::mutex workersMutex_;
  std::vector<Worker> workers_;
};

}  // namespace fedlearn::bridge
