#pragma once
//
// FedLearnCoreModule.h — the shared C++ (CXX) TurboModule behind bridge/specs/NativeFedLearnCore.ts.
//
// DESIGN: the real federated-learning logic lives in the private `do*` methods, which take/return
// plain bridge::* structs (BridgeTypes.h) and call the verified C++ core (ModelManager,
// FedLearnClient, FederatedLoop). They have NO React Native / JSI dependency, so they are
// version-independent and reasoned about on their own merits. The PUBLIC methods are the thin
// JSI/Promise layer the codegen spec calls; they marshal structs <-> jsi::Object field-by-field
// (no hand-built JSON, fixes A6 §L3) and run each `do*` off the JavaScript thread.
//
// ┌─ VERIFY-BEFORE-BUILD (React Native New Architecture, version-specific) ─────────────────────┐
// │ The base class `react::NativeFedLearnCoreCxxSpec<...>`, the exact JSI method signatures, the │
// │ Promise helper (`react::createPromiseAsJSIValue`), and the CallInvoker are produced/required │
// │ by RN codegen for the PINNED RN version. Run `codegen` (npx react-native codegen) and        │
// │ reconcile the signatures below against the generated `NativeFedLearnCoreCxxSpecJSI.h`. None   │
// │ of this compiles without the RN toolchain; the `do*` logic is the part that is portable.     │
// └────────────────────────────────────────────────────────────────────────────────────────────┘
//
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include <ReactCommon/TurboModule.h>             // react::TurboModule, CallInvoker  (RN)
#include <jsi/jsi.h>                              // facebook::jsi                     (RN)
// #include "NativeFedLearnCoreCxxSpecJSI.h"      // <-- GENERATED by RN codegen; include on-build

#include "BridgeTypes.h"
#include "fedlearn/ExecutorchModel.h"
#include "fedlearn/FedLearnClient.h"
#include "fedlearn/FederatedLoop.h"
#include "fedlearn/ModelManager.h"
#include "fedlearn/Types.h"

namespace fedlearn::bridge {

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// The protocol version this client speaks (must equal the server's; RegisterClient rejects on
// mismatch — E1 / 04 §10.1.2). Bump on any breaking contract change.
inline constexpr int kProtocolVersion = 2;

class FedLearnCoreModule : public react::TurboModule {
 public:
  // dataDir: app-private directory (Android filesDir / iOS Documents) holding the gRPC client
  // cert/key/CA and any on-device training data. Passed by the platform layer (OnLoad / .mm).
  FedLearnCoreModule(std::shared_ptr<react::CallInvoker> jsInvoker, std::string dataDir);
  ~FedLearnCoreModule() override;

  // Platform hooks (set by the Android/iOS layer; not part of the JS spec).
  void setMetricsProvider(std::function<DeviceMetrics()> provider);
  // Wiring of on-device training data is the RN app layer's job (15-LLD §13 task 14). Until then
  // a round throws a clear error. This seam lets the app/test supply a validated batch.
  void setTrainingDataFromFiles(const std::string& inputsF32Path,
                                const std::vector<int64_t>& inputShape,
                                const std::string& targetsI64Path);

  // ExecuTorch model load is weights-as-inputs: ModelManager::loadModel needs the trainable
  // param layout + total param count, and the infer .pte (forward(flat,x)->logits) has its OWN
  // sha. The platform layer reads these from the model's sidecar manifest (param_layout /
  // total_param_count / infer_pte path+sha, written by pte_export.py) and supplies them here
  // before loadModel(). (Replaces the old libtorch Module auto-introspection.)
  struct ModelManifest {
    std::vector<fedlearn::ParamSpec> paramLayout;  // trainable name->shape, flat order
    int64_t totalParamCount = 0;                   // incl. frozen, for ModelInfo tier
    std::string inferPtePath;                      // forward(flat,x)->logits graph
    std::string inferSha256;                       // sha of the infer .pte
  };
  void setModelManifest(const ModelManifest& manifest);

  // ---- JSI spec methods (signatures must match the generated CxxSpec; see header banner) ----
  jsi::Value registerClient(jsi::Runtime& rt, jsi::String serverAddress, jsi::String runId,
                            jsi::String clientId, jsi::String enrollmentToken, bool useTls);
  jsi::Value getServerStatus(jsi::Runtime& rt, jsi::String runId);
  jsi::Value stop(jsi::Runtime& rt);
  jsi::Value loadModel(jsi::Runtime& rt, jsi::String modelPath, jsi::String expectedSha256);
  jsi::Value runDeComFLRound(jsi::Runtime& rt, jsi::String runId, jsi::Object config);
  jsi::Value runFedAvgRound(jsi::Runtime& rt, jsi::String runId, jsi::Object config);
  jsi::Value infer(jsi::Runtime& rt, jsi::String inputJson);
  jsi::Value getDeviceMetrics(jsi::Runtime& rt);

 private:
  // ---- pure logic (no JSI; the portable, correct core) ----
  RegisterResult doRegister(const std::string& serverAddress, const std::string& runId,
                            const std::string& clientId, const std::string& enrollmentToken,
                            bool useTls);
  ServerStatus doGetServerStatus(const std::string& runId);
  void doStop();
  ModelInfo doLoadModel(const std::string& modelPath, const std::string& expectedSha256);
  RoundResult doRunDeComFLRound(const std::string& runId, const RoundConfig& cfg);
  RoundResult doRunFedAvgRound(const std::string& runId, const RoundConfig& cfg);
  InferResult doInfer(const std::string& inputJson);
  DeviceMetrics doGetDeviceMetrics();

  // helpers
  void evalBatch(double& outLoss, double& outAccuracy);  // one forward pass on trainingBatch_
  void requireReady() const;                             // model + net + data loaded, else throw

  std::shared_ptr<react::CallInvoker> jsInvoker_;
  std::string dataDir_;

  std::mutex stateMutex_;  // the JS thread calls in; rounds run on a worker — guard shared state
  fedlearn::ModelManager mm_;
  std::unique_ptr<fedlearn::FedLearnClient> net_;
  std::unique_ptr<fedlearn::FederatedLoop> loop_;
  std::unique_ptr<fedlearn::ExecutorchModel> model_;       // loss graph: forward(flat,x,y)->loss
  std::unique_ptr<fedlearn::ExecutorchModel> inferModel_;  // infer graph: forward(flat,x)->logits
  bool modelLoaded_ = false;
  ModelManifest manifest_;
  bool manifestSet_ = false;
  fedlearn::DataBatch trainingBatch_;
  bool dataLoaded_ = false;
  std::string clientId_;
  std::function<DeviceMetrics()> metricsProvider_;
};

}  // namespace fedlearn::bridge
