#!/bin/bash
# =============================================================================
# FedLearn Platform — EC2 Bootstrap Script
# =============================================================================
# Run this ONCE on a fresh Ubuntu 22.04 EC2 instance.
# It installs all runtime dependencies and creates the app directory layout.
#
# Usage:
#   chmod +x ec2-bootstrap.sh
#   ./ec2-bootstrap.sh
# =============================================================================
set -euo pipefail

echo ""
echo "=============================================="
echo " FedLearn EC2 Bootstrap — Starting"
echo "=============================================="
echo ""

# ── Runtime check ────────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
  echo "[ERROR] Please run this script as root: sudo ./ec2-bootstrap.sh"
  exit 1
fi

ACTUAL_USER="${SUDO_USER:-ubuntu}"
HOME_DIR=$(eval echo "~$ACTUAL_USER")
APP_DIR="$HOME_DIR/app"
SCRIPTS_DIR="$APP_DIR/scripts"

echo "[1/7] Updating system packages..."
apt-get update -qq

apt-get install -y --no-install-recommends \
  openjdk-21-jre-headless \
  python3 \
  python3-venv \
  python3-dev \
  python3-pip \
  build-essential \
  cmake \
  curl \
  unzip \
  htop \
  > /dev/null
echo "      ✓ System packages installed"

echo ""
echo "[2/7] Installing CPU-only PyTorch (saves ~2GB vs CUDA build)..."
# Install CPU wheels explicitly BEFORE requirements.txt to prevent pip from
# pulling down the enormous CUDA-enabled torch build.
sudo -u "$ACTUAL_USER" pip3 install --break-system-packages \
  torch \
  torchvision \
  torchaudio \
  --index-url https://download.pytorch.org/whl/cpu
echo "      ✓ PyTorch CPU wheels installed"

echo ""
echo "[3/7] Installing FedLearn Python dependencies (this may take a while)..."
if [[ -f "$HOME_DIR/requirements.txt" ]]; then
  sudo -u "$ACTUAL_USER" pip3 install --break-system-packages -r "$HOME_DIR/requirements.txt"
  echo "      ✓ Python dependencies installed"
else
  echo "      ⚠ WARNING: $HOME_DIR/requirements.txt not found."
  echo "        SCP it first: scp framework/requirements.txt ec2-user@<IP>:~/"
fi

echo ""
echo "[4/7] Creating app directory layout..."
mkdir -p "$APP_DIR"
mkdir -p "$SCRIPTS_DIR"
mkdir -p "$APP_DIR/models"
mkdir -p "$APP_DIR/logs"
mkdir -p "$APP_DIR/data"
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$APP_DIR"
echo "      ✓ Directory layout created at $APP_DIR"

echo ""
echo "[5/7] Provisioning backend secrets (idempotent)..."
# Secrets live in a root-only EnvironmentFile, NOT inline in the systemd unit
# (unit files are world-readable, so inline Environment= lines leak secrets to
# every local user). Generated ONCE: re-running bootstrap never clobbers an
# existing secrets file, so tokens/sessions survive re-bootstraps. To rotate,
# delete /etc/fedlearn/secrets.env, re-run bootstrap, and restart the service.
#
# Graduation path for a real pilot: move these into AWS SSM Parameter Store
# (SecureString) or AWS Secrets Manager and fetch them at boot via the
# instance profile's IAM role, instead of storing them on the instance disk.
SECRETS_DIR="${FEDLEARN_SECRETS_DIR:-/etc/fedlearn}"
SECRETS_FILE="$SECRETS_DIR/secrets.env"
SECRETS_OWNER="${FEDLEARN_SECRETS_OWNER:-root:root}"
mkdir -p "$SECRETS_DIR"
if [ ! -f "$SECRETS_FILE" ]; then
  echo "      Generating new secrets → $SECRETS_FILE"
  # Create the file 0600 BEFORE writing so secrets are never world-readable,
  # not even transiently.
  install -m 600 /dev/null "$SECRETS_FILE"
  cat > "$SECRETS_FILE" <<SECRETS
# FedLearn backend secrets — generated by ec2-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Loaded by systemd via EnvironmentFile=; keep 0600 root:root.
# Re-running bootstrap does NOT regenerate this file (delete it to rotate).
APP_JWT_SECRET=$(openssl rand -hex 64)
APP_INTERNAL_API_KEY=$(openssl rand -hex 32)
# Used when the datasource is password-protected (H2 file-mode picks this up
# on first DB creation; a future Postgres profile consumes it directly).
SPRING_DATASOURCE_PASSWORD=$(openssl rand -hex 24)
SECRETS
else
  echo "      $SECRETS_FILE already exists — keeping existing secrets (no clobber)"
fi
# Always re-assert ownership + permissions, even if the file pre-existed.
chown "$SECRETS_OWNER" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
echo "      ✓ Secrets ready at $SECRETS_FILE (0600, $SECRETS_OWNER)"

echo ""
echo "[6/7] Creating systemd service for FedLearn backend..."
# Create a systemd unit so the backend auto-restarts on crash/reboot
cat > /etc/systemd/system/fedlearn.service <<EOF
[Unit]
Description=FedLearn Platform Backend
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$ACTUAL_USER
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/java -Xmx4g -jar $APP_DIR/app.jar
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=fedlearn

# ── Secrets — root-only env file, generated by ec2-bootstrap.sh ──────────────
# APP_JWT_SECRET / APP_INTERNAL_API_KEY / SPRING_DATASOURCE_PASSWORD live in
# this 0600 root:root file. Never put secrets inline here: this unit file is
# world-readable.
EnvironmentFile=$SECRETS_FILE

# ── Non-secret settings (pre-configured, no changes needed) ─────────────────
Environment="SPRING_PROFILES_ACTIVE=ec2demo"
Environment="FEDLEARN_PYTHON=python3"
Environment="PYTHON_EXECUTABLE_PATH=$SCRIPTS_DIR/run_init_model.sh"
Environment="PYTHON_SCRIPT_FL_SERVER_PATH=$SCRIPTS_DIR/run_fl_server.sh"
Environment="FEATURE_LOG_PERSISTENCE=false"
Environment="FEATURE_ROUND_RESULTS=true"
# Not a secret — set to your frontend origin(s) before starting:
# Environment="CORS_ALLOWED_ORIGINS=http://localhost:5173"

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
echo "      ✓ systemd service created (not started yet)"
echo "        Secrets are auto-loaded from $SECRETS_FILE — do not edit them into the unit."
echo "        Set CORS_ALLOWED_ORIGINS in /etc/systemd/system/fedlearn.service, then:"
echo "        sudo systemctl daemon-reload && sudo systemctl enable fedlearn && sudo systemctl start fedlearn"

echo ""
echo "[7/7] Verifying Java version..."
java -version 2>&1 | head -1
echo "      ✓ Java OK"

echo ""
echo "=============================================="
echo " Bootstrap complete!"
echo ""
echo " Next steps:"
echo "   1. SCP the JAR and scripts from your Mac (run deploy-to-aws.sh)"
echo "   2. Secrets were generated into $SECRETS_FILE (0600, root-only) —"
echo "      only CORS_ALLOWED_ORIGINS still needs setting in the unit file"
echo "   3. sudo systemctl enable fedlearn && sudo systemctl start fedlearn"
echo "   4. sudo journalctl -u fedlearn -f   (tail logs)"
echo "=============================================="
