#!/bin/bash
# =============================================================================
# FedLearn Platform — EC2 Bootstrap Script
# =============================================================================
# Run this ONCE on a fresh Ubuntu 22.04 EC2 instance.
# It installs all runtime dependencies and creates the app directory layout.
# Safe to re-run: secrets, certificates, and keypairs are never clobbered.
#
# Usage:
#   chmod +x ec2-bootstrap.sh
#   ./ec2-bootstrap.sh
#
# Optional env overrides (all non-secret):
#   FEDLEARN_DOMAIN             Public domain for HTTPS (default: fedlearn.duckdns.org)
#   FEDLEARN_LETSENCRYPT_EMAIL  Contact email for Let's Encrypt expiry notices
#                               (default: none — registers without an email)
#   FEDLEARN_NGINX_TEMPLATE     Path to the nginx template uploaded by
#                               deploy-to-aws.sh (default: ~/fedlearn-nginx.conf)
#   FEDLEARN_GRPC_TLS=0         DISABLE FL gRPC TLS (escape hatch). Default: TLS is
#                               ON/fail-closed (SE-2); =0 re-opens plaintext for a
#                               mixed-version client rollout. See deploy/TLS.md.
# =============================================================================
set -euo pipefail

echo ""
echo "=============================================="
echo " FedLearn EC2 Bootstrap — Starting"
echo "=============================================="
echo ""

# ── Runtime check ────────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
  echo "[ERROR] Please run this script as root: sudo ./ec2-bootstrap.sh"
  exit 1
fi

ACTUAL_USER="${SUDO_USER:-ubuntu}"
HOME_DIR=$(eval echo "~$ACTUAL_USER")
APP_DIR="$HOME_DIR/app"
SCRIPTS_DIR="$APP_DIR/scripts"

echo "[1/9] Updating system packages..."
apt-get update -qq

apt-get install -y --no-install-recommends \
  openjdk-21-jre-headless \
  python3 \
  python3-venv \
  python3-dev \
  python3-pip \
  build-essential \
  cmake \
  curl \
  unzip \
  htop \
  nginx \
  certbot \
  > /dev/null
echo "      ✓ System packages installed"

echo ""
echo "[2/9] Installing CPU-only PyTorch (saves ~2GB vs CUDA build)..."
# Install CPU wheels explicitly BEFORE requirements.txt to prevent pip from
# pulling down the enormous CUDA-enabled torch build.
sudo -u "$ACTUAL_USER" pip3 install --break-system-packages \
  torch \
  torchvision \
  torchaudio \
  --index-url https://download.pytorch.org/whl/cpu
echo "      ✓ PyTorch CPU wheels installed"

echo ""
echo "[3/9] Installing FedLearn Python dependencies (this may take a while)..."
if [[ -f "$HOME_DIR/requirements.txt" ]]; then
  sudo -u "$ACTUAL_USER" pip3 install --break-system-packages -r "$HOME_DIR/requirements.txt"
  echo "      ✓ Python dependencies installed"
else
  echo "      ⚠ WARNING: $HOME_DIR/requirements.txt not found."
  echo "        SCP it first: scp framework/requirements.txt ec2-user@<IP>:~/"
fi

echo ""
echo "[4/9] Creating app directory layout..."
mkdir -p "$APP_DIR"
mkdir -p "$SCRIPTS_DIR"
mkdir -p "$APP_DIR/models"
mkdir -p "$APP_DIR/logs"
mkdir -p "$APP_DIR/data"
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$APP_DIR"
echo "      ✓ Directory layout created at $APP_DIR"

echo ""
echo "[5/9] Provisioning backend secrets (idempotent)..."
# Secrets live in a root-only EnvironmentFile, NOT inline in the systemd unit
# (unit files are world-readable, so inline Environment= lines leak secrets to
# every local user). Generated ONCE: re-running bootstrap never clobbers an
# existing secrets file, so tokens/sessions survive re-bootstraps. To rotate,
# delete /etc/fedlearn/secrets.env, re-run bootstrap, and restart the service.
#
# Graduation path for a real pilot: move these into AWS SSM Parameter Store
# (SecureString) or AWS Secrets Manager and fetch them at boot via the
# instance profile's IAM role, instead of storing them on the instance disk.
SECRETS_DIR="${FEDLEARN_SECRETS_DIR:-/etc/fedlearn}"
SECRETS_FILE="$SECRETS_DIR/secrets.env"
SECRETS_OWNER="${FEDLEARN_SECRETS_OWNER:-root:root}"
mkdir -p "$SECRETS_DIR"
if [ ! -f "$SECRETS_FILE" ]; then
  echo "      Generating new secrets → $SECRETS_FILE"
  # Create the file 0600 BEFORE writing so secrets are never world-readable,
  # not even transiently.
  install -m 600 /dev/null "$SECRETS_FILE"
  cat > "$SECRETS_FILE" <<SECRETS
# FedLearn backend secrets — generated by ec2-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Loaded by systemd via EnvironmentFile=; keep 0600 root:root.
# Re-running bootstrap does NOT regenerate this file (delete it to rotate).
APP_JWT_SECRET=$(openssl rand -hex 64)
APP_INTERNAL_API_KEY=$(openssl rand -hex 32)
# Used when the datasource is password-protected (H2 file-mode picks this up
# on first DB creation; a future Postgres profile consumes it directly).
SPRING_DATASOURCE_PASSWORD=$(openssl rand -hex 24)
SECRETS
else
  echo "      $SECRETS_FILE already exists — keeping existing secrets (no clobber)"
fi
# Always re-assert ownership + permissions, even if the file pre-existed.
chown "$SECRETS_OWNER" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
echo "      ✓ Secrets ready at $SECRETS_FILE (0600, $SECRETS_OWNER)"

echo ""
echo "[6/9] Provisioning nginx + certbot HTTPS (idempotent)..."
# TLS at the edge: nginx terminates HTTPS on :443 and proxies to Spring Boot on
# 127.0.0.1:8081. Certificate issuance + renewal is automated with certbot in
# WEBROOT mode (certbot never rewrites our server block — the committed
# template in deploy/nginx/fedlearn.conf stays the single source of truth).
# Re-running bootstrap never re-requests a certificate that already exists.
#
# Two-phase install, because the TLS server block references the Let's Encrypt
# cert paths and `nginx -t` fails while they don't exist yet:
#   Phase 1 (no cert): minimal HTTP-only config — ACME webroot + plain proxy —
#            then `certbot certonly --webroot` for $DOMAIN.
#   Phase 2 (cert present): render the committed TLS template (http→https
#            redirect, HSTS, /ws-logs WebSocket upgrade) and reload.
DOMAIN="${FEDLEARN_DOMAIN:-fedlearn.duckdns.org}"
LE_EMAIL="${FEDLEARN_LETSENCRYPT_EMAIL:-}"   # optional, not a secret
NGINX_TEMPLATE="${FEDLEARN_NGINX_TEMPLATE:-$HOME_DIR/fedlearn-nginx.conf}"
LIVE_CERT="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
ACME_WEBROOT="/var/www/certbot"
SITE_AVAIL="/etc/nginx/sites-available/fedlearn.conf"
SITE_ENABLED="/etc/nginx/sites-enabled/fedlearn.conf"

if [[ ! -f "$NGINX_TEMPLATE" ]]; then
  echo "      ⚠ WARNING: nginx template not found at $NGINX_TEMPLATE — skipping HTTPS setup."
  echo "        deploy-to-aws.sh uploads it (from deploy/nginx/fedlearn.conf);"
  echo "        SCP it manually or re-run bootstrap after the next deploy."
else
  mkdir -p "$ACME_WEBROOT"
  rm -f /etc/nginx/sites-enabled/default

  if [[ ! -f "$LIVE_CERT" ]]; then
    echo "      No certificate for $DOMAIN yet — installing HTTP-only config for the ACME challenge..."
    cat > "$SITE_AVAIL" <<HTTPCONF
# Bootstrap (pre-certificate) config, written by ec2-bootstrap.sh. Replaced by
# the TLS server block from deploy/nginx/fedlearn.conf once certbot has issued
# a certificate for $DOMAIN.
map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    location /.well-known/acme-challenge/ { root $ACME_WEBROOT; }
    client_max_body_size 2g;
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }
    location /ws-logs {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;
        proxy_set_header Host              \$host;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
HTTPCONF
    ln -sf "$SITE_AVAIL" "$SITE_ENABLED"
    nginx -t
    systemctl enable --now nginx >/dev/null 2>&1
    systemctl reload nginx

    echo "      Requesting Let's Encrypt certificate for $DOMAIN (webroot)..."
    EMAIL_ARGS=(--register-unsafely-without-email)
    if [[ -n "$LE_EMAIL" ]]; then
      EMAIL_ARGS=(-m "$LE_EMAIL" --no-eff-email)
    fi
    if certbot certonly --webroot -w "$ACME_WEBROOT" -d "$DOMAIN" \
         --non-interactive --agree-tos --keep-until-expiring \
         --deploy-hook "systemctl reload nginx" \
         "${EMAIL_ARGS[@]}"; then
      echo "      ✓ Certificate issued for $DOMAIN"
    else
      echo "      ⚠ WARNING: certbot issuance FAILED. DNS for $DOMAIN must point at this"
      echo "        instance and :80 must be open in the security group. Staying HTTP-only;"
      echo "        fix DNS/firewall and re-run bootstrap (it will pick up where it left off)."
    fi
  else
    echo "      Certificate for $DOMAIN already exists — not re-requesting (no clobber)"
  fi

  if [[ -f "$LIVE_CERT" ]]; then
    sed "s/__FEDLEARN_DOMAIN__/$DOMAIN/g" "$NGINX_TEMPLATE" > "$SITE_AVAIL"
    ln -sf "$SITE_AVAIL" "$SITE_ENABLED"
    nginx -t
    systemctl enable --now nginx >/dev/null 2>&1
    systemctl reload nginx
    # Auto-renewal: the Ubuntu certbot package ships certbot.timer, which runs
    # `certbot renew` twice daily; the --deploy-hook recorded at issuance
    # reloads nginx after each renewal. Enable it explicitly rather than
    # relying on packaging defaults.
    systemctl enable --now certbot.timer >/dev/null 2>&1 || true
    echo "      ✓ HTTPS live: https://$DOMAIN → 127.0.0.1:8081 (auto-renew via certbot.timer)"
  fi
fi

echo ""
echo "[7/9] Provisioning FL gRPC TLS material (idempotent; serving is OPT-IN)..."
# The FL servers listen on ports 50000-50010 and BYPASS nginx entirely, so the
# edge certificate does not cover them (audit #37: gRPC is plaintext over WAN).
# SE-2 already wired a fail-closed TLS path into the framework + backend; here
# we provision the cert material so enabling it is a one-line flip in the
# systemd unit below. A long-lived self-signed keypair is used instead of the
# Let's Encrypt cert because (a) the LE live dir is root-only while FL servers
# run as $ACTUAL_USER, and (b) LE's 90-day rotation would silently break
# clients that pin the cert. Clients trust it by pinning the PUBLIC cert as
# their root CA (FEDLEARN_GRPC_ROOT_CERT). Full story: deploy/TLS.md.
GRPC_TLS_DIR="${FEDLEARN_GRPC_TLS_DIR:-/etc/fedlearn/grpc}"
GRPC_KEY="$GRPC_TLS_DIR/server.key"
GRPC_CERT="$GRPC_TLS_DIR/server.crt"
mkdir -p "$GRPC_TLS_DIR"
if [[ ! -f "$GRPC_KEY" || ! -f "$GRPC_CERT" ]]; then
  openssl req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes \
    -keyout "$GRPC_KEY" -out "$GRPC_CERT" \
    -subj "/CN=$DOMAIN" \
    -addext "subjectAltName=DNS:$DOMAIN" 2>/dev/null
  echo "      ✓ Self-signed gRPC keypair generated at $GRPC_TLS_DIR (CN=$DOMAIN)"
else
  echo "      $GRPC_CERT already exists — keeping existing keypair (no clobber)"
fi
# The FL server child runs as $ACTUAL_USER (spawned by the backend), so it must
# be able to read the private key; nobody else needs to.
chown "$ACTUAL_USER:$ACTUAL_USER" "$GRPC_KEY" "$GRPC_CERT"
chmod 600 "$GRPC_KEY"
chmod 644 "$GRPC_CERT"

# FL gRPC TLS is now the ec2demo/production DEFAULT (app.fl.require-tls=true in
# application-ec2demo.properties, SE-2 full flip). The backend spawns each FL server fail-closed
# (FEDLEARN_GRPC_USE_TLS=1 + FEDLEARN_REQUIRE_TLS=1) and REFUSES to bind plaintext, so the unit
# MUST hand it the keypair below (always active) — otherwise NO FL server can launch. Every client
# must dial with FEDLEARN_GRPC_USE_TLS=1 + FEDLEARN_GRPC_ROOT_CERT=<copy of server.crt>.
#
# ESCAPE HATCH: bootstrap with FEDLEARN_GRPC_TLS=0 to re-open plaintext for a mixed-version rollout
# (existing plaintext desktop/mobile clients that predate TLS). It emits APP_FL_REQUIRE_TLS=false
# in the unit, which OUTRANKS the profile default (OS env > properties file, Spring relaxed binding).
GRPC_PLAINTEXT_PREFIX="# "   # default: keep the plaintext override commented out -> TLS stays on
if [[ "${FEDLEARN_GRPC_TLS:-1}" == "0" ]]; then
  GRPC_PLAINTEXT_PREFIX=""
  echo "      FL gRPC TLS: DISABLED via escape hatch (FEDLEARN_GRPC_TLS=0 -> APP_FL_REQUIRE_TLS=false)"
else
  echo "      FL gRPC TLS: ENABLED (fail-closed default); serving keypair from $GRPC_TLS_DIR"
fi

# Auth cookie Secure flag: ON automatically once a Let's Encrypt cert exists (HTTPS is live at the
# nginx edge), OFF during a plain-HTTP bring-up so the browser doesn't silently drop the login
# cookie before the cert is issued. Env var overrides application-ec2demo.properties (env > file).
COOKIE_SECURE_PREFIX="# "
if [[ -f "$LIVE_CERT" ]]; then
  COOKIE_SECURE_PREFIX=""
  echo "      Auth cookie Secure: ENABLED (Let's Encrypt cert present — HTTPS live)"
else
  echo "      Auth cookie Secure: OFF (no cert yet — plain-HTTP bring-up; re-run after issuance)"
fi

echo ""
echo "[8/9] Creating systemd service for FedLearn backend..."
# Create a systemd unit so the backend auto-restarts on crash/reboot
cat > /etc/systemd/system/fedlearn.service <<EOF
[Unit]
Description=FedLearn Platform Backend
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$ACTUAL_USER
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/java -Xmx4g -jar $APP_DIR/app.jar
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=fedlearn

# ── Secrets — root-only env file, generated by ec2-bootstrap.sh ──────────────
# APP_JWT_SECRET / APP_INTERNAL_API_KEY / SPRING_DATASOURCE_PASSWORD live in
# this 0600 root:root file. Never put secrets inline here: this unit file is
# world-readable.
EnvironmentFile=$SECRETS_FILE

# ── Non-secret settings (pre-configured, no changes needed) ─────────────────
Environment="SPRING_PROFILES_ACTIVE=ec2demo"
Environment="FEDLEARN_PYTHON=python3"
Environment="PYTHON_EXECUTABLE_PATH=$SCRIPTS_DIR/run_init_model.sh"
Environment="PYTHON_SCRIPT_FL_SERVER_PATH=$SCRIPTS_DIR/run_fl_server.sh"
Environment="FEATURE_LOG_PERSISTENCE=false"
Environment="FEATURE_ROUND_RESULTS=true"
# Not a secret — set to your frontend origin(s) before starting:
# Environment="CORS_ALLOWED_ORIGINS=http://localhost:5173"
# Auth cookie Secure — auto-enabled when a Let's Encrypt cert is present (HTTPS live at the nginx
# edge), commented during a plain-HTTP bring-up so the login cookie isn't dropped before the cert
# exists. Re-run ec2-bootstrap.sh after issuance to flip it on.
${COOKIE_SECURE_PREFIX}Environment="APP_AUTH_COOKIE_SECURE=true"

# ── FL gRPC TLS (SE-2): TLS is the fail-closed DEFAULT ───────────────────────
# The FL servers (ports 50000-50010) bypass nginx. app.fl.require-tls=true (ec2demo profile
# default) makes the backend spawn them with FEDLEARN_GRPC_USE_TLS=1 + FEDLEARN_REQUIRE_TLS=1
# (fail-closed: an FL server that cannot serve TLS refuses to start), so it MUST read the keypair
# below — provisioned above and left ACTIVE here. Configure every client with
# FEDLEARN_GRPC_USE_TLS=1 and FEDLEARN_GRPC_ROOT_CERT=<server.crt copy>.
# Plaintext escape hatch (mixed-version rollout): the APP_FL_REQUIRE_TLS=false line below is
# emitted (uncommented) ONLY when bootstrapped with FEDLEARN_GRPC_TLS=0, forcing plaintext.
# Details + Tailscale alternative: deploy/TLS.md.
${GRPC_PLAINTEXT_PREFIX}Environment="APP_FL_REQUIRE_TLS=false"
Environment="FEDLEARN_GRPC_SERVER_KEY=$GRPC_KEY"
Environment="FEDLEARN_GRPC_SERVER_CERT=$GRPC_CERT"

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
echo "      ✓ systemd service created (not started yet)"
echo "        Secrets are auto-loaded from $SECRETS_FILE — do not edit them into the unit."
echo "        Set CORS_ALLOWED_ORIGINS in /etc/systemd/system/fedlearn.service, then:"
echo "        sudo systemctl daemon-reload && sudo systemctl enable fedlearn && sudo systemctl start fedlearn"

echo ""
echo "[9/9] Verifying Java version..."
java -version 2>&1 | head -1
echo "      ✓ Java OK"

echo ""
echo "=============================================="
echo " Bootstrap complete!"
echo ""
echo " Next steps:"
echo "   1. SCP the JAR and scripts from your Mac (run deploy-to-aws.sh)"
echo "   2. Secrets were generated into $SECRETS_FILE (0600, root-only) —"
echo "      only CORS_ALLOWED_ORIGINS still needs setting in the unit file"
echo "   3. sudo systemctl enable fedlearn && sudo systemctl start fedlearn"
echo "   4. sudo journalctl -u fedlearn -f   (tail logs)"
echo ""
echo " TLS status:"
if [[ -f "$LIVE_CERT" ]]; then
  echo "   • HTTPS: live at https://$DOMAIN (auto-renewed by certbot.timer)"
else
  echo "   • HTTPS: NOT provisioned (cert issuance skipped/failed) — HTTP only."
  echo "     Point DNS for $DOMAIN here, open :80/:443, re-run bootstrap."
fi
echo "   • FL gRPC: TLS fail-closed by default (keypair at $GRPC_TLS_DIR); FEDLEARN_GRPC_TLS=0 to re-open plaintext"
echo "     (see the unit file + deploy/TLS.md)"
echo "=============================================="
