// GENERATED by design/build-tokens.mjs — DO NOT EDIT. Edit design/tokens.json and re-run.
export const tokens = {
  "colorLight": {
    "canvas": "#FBF9F6",
    "surface-1": "#FFFFFF",
    "surface-2": "#F4F1EC",
    "surface-3": "#ECE7DF",
    "code-well": "#F6F3EE",
    "hairline": "#E7E1D8",
    "line": "#D8D1C5",
    "fg": "#1A1714",
    "fg-muted": "#6B6358",
    "fg-subtle": "#938A7D",
    "accent": "#C56A1E",
    "accent-hover": "#A9591A",
    "accent-fg": "#FFFFFF",
    "success": "#1F9D57",
    "warning": "#B07D0A",
    "danger": "#CE3F38",
    "running": "#C56A1E"
  },
  "colorDark": {
    "canvas": "#000000",
    "surface-1": "#0B0A09",
    "surface-2": "#141210",
    "surface-3": "#1E1B17",
    "code-well": "#050504",
    "hairline": "rgba(255, 244, 232, 0.08)",
    "line": "rgba(255, 244, 232, 0.15)",
    "fg": "#F5F1EA",
    "fg-muted": "#A8A096",
    "fg-subtle": "#6E665C",
    "accent": "#F7A35C",
    "accent-hover": "#FFB877",
    "accent-fg": "#1C0F03",
    "success": "#5FD39B",
    "warning": "#EBC152",
    "danger": "#FF6B5E",
    "running": "#F7A35C"
  },
  "series": [
    "#F7A35C",
    "#5FD39B",
    "#6FA8FF",
    "#C79BFF",
    "#EBC152",
    "#FF8CA6",
    "#4FD6C9",
    "#A8A096"
  ],
  "radius": {
    "sm": 6,
    "md": 9,
    "lg": 12,
    "card": 16,
    "pill": 9999
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "6": 24,
    "8": 32,
    "12": 48,
    "16": 64,
    "0.5": 2
  },
  "duration": {
    "fast": 120,
    "base": 180,
    "slow": 280
  },
  "font": {
    "sans": "Hanken Grotesk",
    "display": "Hanken Grotesk",
    "mono": "JetBrains Mono"
  },
  "text": {
    "caption": {
      "size": 12,
      "line": 16,
      "tracking": 0.1,
      "weight": 500
    },
    "label": {
      "size": 13,
      "line": 18,
      "tracking": 0,
      "weight": 500
    },
    "body": {
      "size": 14,
      "line": 20,
      "tracking": 0,
      "weight": 400
    },
    "body-lg": {
      "size": 16,
      "line": 24,
      "tracking": -0.05,
      "weight": 400
    },
    "h4": {
      "size": 18,
      "line": 24,
      "tracking": -0.2,
      "weight": 600
    },
    "h3": {
      "size": 22,
      "line": 28,
      "tracking": -0.4,
      "weight": 600
    },
    "h2": {
      "size": 30,
      "line": 36,
      "tracking": -0.8,
      "weight": 600
    },
    "h1": {
      "size": 40,
      "line": 44,
      "tracking": -1.4,
      "weight": 700
    }
  }
} as const;

export type ColorToken = keyof typeof tokens.colorLight;
export default tokens;
