// GENERATED by design/build-tokens.mjs — DO NOT EDIT. Edit design/tokens.json and re-run.
export const tokens = {
  "colorLight": {
    "canvas": "#F6F3EE",
    "surface-1": "#FFFFFF",
    "surface-2": "#F1EDE4",
    "surface-3": "#EAE5DC",
    "code-well": "#EFEBE2",
    "code-fg": "#191A1C",
    "hairline": "#E7E2D9",
    "line": "#D6D0C4",
    "fg": "#191A1C",
    "fg-muted": "#6B6760",
    "fg-subtle": "#736E66",
    "accent": "#1C314D",
    "accent-hover": "#14243A",
    "accent-fg": "#FFFFFF",
    "success": "#2E6B4E",
    "warning": "#9A5B12",
    "danger": "#8F3C37",
    "running": "#3A5A76",
    "scrim": "rgba(25, 26, 28, 0.45)"
  },
  "colorDark": {
    "canvas": "#0B1622",
    "surface-1": "#121F2E",
    "surface-2": "#18283A",
    "surface-3": "#1B2C40",
    "code-well": "#0A131D",
    "code-fg": "#C9D6E4",
    "hairline": "#25374A",
    "line": "#2F445A",
    "fg": "#EAF0F6",
    "fg-muted": "#B4C0CE",
    "fg-subtle": "#8FA0B2",
    "accent": "#4F8AC9",
    "accent-hover": "#82AFE0",
    "accent-fg": "#08111B",
    "success": "#5FB87A",
    "warning": "#D8B878",
    "danger": "#E0584A",
    "running": "#82AFE0",
    "scrim": "rgba(0, 0, 0, 0.6)"
  },
  "series": [
    "#3565B0",
    "#008300",
    "#E87BA4",
    "#EDA100",
    "#1BAF7A",
    "#EB6834",
    "#4A3AA7",
    "#E34948"
  ],
  "radius": {
    "sm": 4,
    "md": 6,
    "lg": 10,
    "card": 12,
    "pill": 9999
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "6": 24,
    "8": 32,
    "12": 48,
    "16": 64,
    "0.5": 2
  },
  "duration": {
    "fast": 120,
    "base": 180,
    "slow": 280
  },
  "font": {
    "sans": "Hanken Grotesk",
    "display": "Hanken Grotesk",
    "mono": "JetBrains Mono"
  },
  "text": {
    "caption": {
      "size": 12,
      "line": 16,
      "tracking": 0.1,
      "weight": 500
    },
    "label": {
      "size": 13,
      "line": 18,
      "tracking": 0,
      "weight": 500
    },
    "body": {
      "size": 14,
      "line": 20,
      "tracking": 0,
      "weight": 400
    },
    "body-lg": {
      "size": 16,
      "line": 24,
      "tracking": -0.05,
      "weight": 400
    },
    "h4": {
      "size": 18,
      "line": 24,
      "tracking": -0.2,
      "weight": 600
    },
    "h3": {
      "size": 22,
      "line": 28,
      "tracking": -0.4,
      "weight": 600
    },
    "h2": {
      "size": 30,
      "line": 36,
      "tracking": -0.6,
      "weight": 600
    },
    "h1": {
      "size": 40,
      "line": 44,
      "tracking": -1,
      "weight": 700
    }
  }
} as const;

export type ColorToken = keyof typeof tokens.colorLight;
export default tokens;
