// GENERATED by design/build-tokens.mjs — DO NOT EDIT. Edit design/tokens.json and re-run.
export const tokens = {
  "colorLight": {
    "canvas": "#FCFCFD",
    "surface-1": "#FFFFFF",
    "surface-2": "#F6F7F9",
    "surface-3": "#F0F2F5",
    "code-well": "#F4F6F8",
    "hairline": "#E6E8EC",
    "line": "#D5D8DE",
    "fg": "#16181D",
    "fg-muted": "#5B6470",
    "fg-subtle": "#8A93A0",
    "accent": "#0E8FB8",
    "accent-hover": "#0B7D9F",
    "accent-fg": "#FFFFFF",
    "success": "#1F9D57",
    "warning": "#B8860B",
    "danger": "#D23F3F",
    "running": "#0E8FB8"
  },
  "colorDark": {
    "canvas": "#0A0C10",
    "surface-1": "#0F1216",
    "surface-2": "#14181D",
    "surface-3": "#191E24",
    "code-well": "#06080B",
    "hairline": "rgba(255, 255, 255, 0.07)",
    "line": "rgba(255, 255, 255, 0.13)",
    "fg": "#ECEEF2",
    "fg-muted": "#8A93A0",
    "fg-subtle": "#5B6470",
    "accent": "#22B8D6",
    "accent-hover": "#3FC6E0",
    "accent-fg": "#06121A",
    "success": "#34D399",
    "warning": "#FBBF24",
    "danger": "#F87171",
    "running": "#22B8D6"
  },
  "series": [
    "#0072B2",
    "#D55E00",
    "#009E73",
    "#E69F00",
    "#56B4E9",
    "#CC79A7",
    "#F0E442",
    "#8A93A0"
  ],
  "radius": {
    "sm": 4,
    "md": 6,
    "lg": 8,
    "card": 12,
    "pill": 9999
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "6": 24,
    "8": 32,
    "12": 48,
    "16": 64,
    "0.5": 2
  },
  "duration": {
    "fast": 120,
    "base": 160,
    "slow": 240
  },
  "font": {
    "sans": "Inter",
    "mono": "JetBrains Mono"
  },
  "text": {
    "caption": {
      "size": 12,
      "line": 16,
      "tracking": 0.1,
      "weight": 500
    },
    "label": {
      "size": 13,
      "line": 18,
      "tracking": 0,
      "weight": 500
    },
    "body": {
      "size": 14,
      "line": 20,
      "tracking": 0,
      "weight": 400
    },
    "body-lg": {
      "size": 16,
      "line": 24,
      "tracking": -0.05,
      "weight": 400
    },
    "h4": {
      "size": 18,
      "line": 24,
      "tracking": -0.2,
      "weight": 600
    },
    "h3": {
      "size": 22,
      "line": 28,
      "tracking": -0.4,
      "weight": 600
    },
    "h2": {
      "size": 28,
      "line": 34,
      "tracking": -0.7,
      "weight": 600
    },
    "h1": {
      "size": 36,
      "line": 42,
      "tracking": -1.2,
      "weight": 600
    }
  }
} as const;

export type ColorToken = keyof typeof tokens.colorLight;
export default tokens;
